import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatPace, formatTime } from './paceCalc';

function sanitize(str) {
  return (str || '').toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
}

function formatDate(isoDate, { weekday } = {}) {
  if (!isoDate) return null;
  const [y, m, d] = isoDate.split('-').map(Number);
  return new Date(y, m - 1, d).toLocaleDateString(undefined, {
    ...(weekday ? { weekday: 'long' } : {}),
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
}

export function downloadPdf(segments, raceInfo, elevationSummary, chartImageData) {
  const { raceName, distanceKm, unit, goalTime, splitMode, avgPace, courseName, raceDate } = raceInfo;
  const hasElevation = elevationSummary != null && segments[0]?.adjustedPaceSeconds != null;
  const paceUnit = unit === 'mile' ? '/mi' : '/km';
  const paceConvert = unit === 'mile' ? 1.60934 : 1;

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = margin;

  // White background
  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, pageW, 297, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(242, 126, 0);
  const title = courseName ? `${courseName} — Race Pace Plan` : 'Race Pace Plan';
  doc.text(title, margin, y + 8);
  y += 18;

  // Formatted date line below title (with weekday, for PDF)
  const formattedDateLong = formatDate(raceDate, { weekday: true });
  if (formattedDateLong) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(formattedDateLong, margin, y);
    y += 7;
  }

  // Info grid
  const infoItems = [
    ['Race', raceName || '—'],
    ['Distance', `${distanceKm} km`],
    ...(goalTime ? [['Goal Time', goalTime]] : []),
    ['Strategy', splitMode || '—'],
    ...(avgPace ? [['Avg Pace', avgPace]] : []),
  ];
  if (hasElevation) {
    infoItems.push(['Total Ascent', `+${elevationSummary.totalAscent}m`]);
    infoItems.push(['Total Descent', `-${elevationSummary.totalDescent}m`]);
  }

  const colW = (pageW - margin * 2) / 2;
  doc.setFontSize(9);
  infoItems.forEach(([label, val], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = margin + col * colW;
    const iy = y + row * 7;
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(160, 160, 160);
    doc.text(label.toUpperCase(), x, iy);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.text(String(val), x + 28, iy);
  });

  y += Math.ceil(infoItems.length / 2) * 7 + 6;

  // Elevation chart image
  if (chartImageData) {
    try {
      doc.addImage(chartImageData, 'PNG', margin, y, pageW - margin * 2, 22);
      y += 26;
    } catch (_) {
      // skip if image embedding fails
    }
  }

  // Splits table
  const head = [['Seg', 'Distance', `Pace${paceUnit}`, 'Cumulative']];
  if (hasElevation) head[0].push('Elev', 'Grade', `Adj Pace${paceUnit}`);

  const body = segments.map((seg) => {
    const dist =
      unit === 'mile'
        ? `${seg.distanceMarker.toFixed(1)} mi`
        : `${seg.distanceMarker.toFixed(1)} km`;
    const pace = formatPace(seg.paceSeconds * paceConvert);
    const cum = formatTime(seg.cumulativeSeconds);
    const row = [String(seg.segment), dist, pace, cum];
    if (hasElevation) {
      const nc = seg.netChange ?? 0;
      row.push(`${nc >= 0 ? '+' : ''}${nc}m`);
      row.push(`${(seg.gradientPercent || 0).toFixed(1)}%`);
      row.push(formatPace(seg.adjustedPaceSeconds * paceConvert));
    }
    return row;
  });

  autoTable(doc, {
    startY: y,
    head,
    body,
    theme: 'grid',
    headStyles: {
      fillColor: [242, 126, 0],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { left: margin, right: margin },
    didParseCell: (data) => {
      if (data.section === 'body' && data.row.index === body.length - 1) {
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  const finalY = doc.lastAutoTable?.finalY ?? y + 20;
  doc.setFontSize(8);
  doc.setTextColor(180, 180, 180);
  doc.text('Generated by Race Pace Splitter', margin, finalY + 8);
  doc.text(new Date().toLocaleDateString(), pageW - margin, finalY + 8, { align: 'right' });

  const fileBase = courseName ? sanitize(courseName) : `race-splits-${sanitize(raceName)}`;
  const goalSuffix = goalTime ? `-${sanitize(goalTime)}` : '';
  doc.save(`${fileBase}${goalSuffix}.pdf`);
}
